# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.configuration-cache.problems=warn

# TODO Remove for production
org.gradle.java.home=/usr/lib/jvm/java-21-openjdk-amd64

# Project
version=1.0.0
group=sylvan.modifiers
java_version=21
display_url=https://github.com/SylvanSerenity/ReforgedModifiers
issues_url=https://github.com/SylvanSerenity/ReforgedModifiers/issues

# Mod options
mod_id=modifiers
mod_name=Reforged Modifiers
mod_author=SylvanSerenity
license=CC0 1.0 Universal
credits=\\n\u00a76\u00a7oCursedFlames\u00a7r for making the original Modifiers mod.\\n\u00a7c\u00a7oMCTeamPotato\u00a7r for making the Remodified mod.
description=Adds equipment modifiers which modifies their attributes. Like \u00a7aTerraria\u00a7r!

# Minecraft
minecraft_version_range=[1.21,1.22)
minecraft_version=1.21.1
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric
fabric_version=0.116.5+1.21.1
fabric_loader_version=0.16.9

# NeoForge
neoforge_version=21.1.238
neoforge_loader_version_range=[4,)

# Dependencies
jei_version=19.39.0.372
